var f_color=[
	{name:"Signal",color:"#00AEEF"},
	{name:"Propeptide",color:"#104A7F"},
	{name:"Chain",color:"#6E7BA2"},
    {name:"Peptide",color:"#DAF1FC"},
    {name:"Active site",color:"#542C88"},
    {name:"Transmembrane",color:"#BE1E2D"},
    {name:"Intramembrane",color:"#FAD2D9"},
    {name:"Domain",color:"#ED1C24"},
    {name:"Repeat",color:"#EA7075"},
    {name:"Site",color:"#D49DC7"},
    {name:"Calcium binding",color:"#F8AFB3"},
    {name:"Zinc finger",color:"#D97D25"},   
    {name:"DNA binding",color:"#F89420"},
    {name:"Nucleotide binding",color:"#F6B667"},
    {name:"Metal binding",color:"#A084BD"},
    {name:"Region",color:"#F9ED32"},
    {name:"Coiled coil",color:"#FBE3C7"},
    {name:"Motif",color:"#C1A72F"},
    {name:"Compositional bias",color:"#E8C51D"},
    {name:"Binding site",color:"#B2509E"},
    {name:"Non-standard residue",color:"#ED2891"},
    {name:"Modified residue",color:"#542C88"},
    {name:"Lipidation",color:"#A084BD"},
    {name:"Glycosylation",color:"#D3C3E0"},
    {name:"Alternative sequence",color:"#CACCDB"},
    {name:"Disulfide bond",color:"#B2509E"},
    {name:"Cross-link",color:"#D49DC7"},
    {name:"Helix",color:"#3953A4"},
    {name:"Turn",color:"#754C29"},
    {name:"Natural variant",color:"#CCD1D1"},
    {name:"Beta strand",color:"#CEAC8F"},
    {name:"Topological domain",color:"#7E1918"},
    {name:"Initiator methionine",color:"#007EB5"},
    {name:"Transit peptide",color:"#9EDDF9"}
    ]
    